version: 1.0.{build}
build: off

install:
  - set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  - activate test-environment
# test_script:
#   - cmd: conda help
