version: 1.0.{build}
build: off

environment:
  CONDA_ENV_NAME: conda-pack-build
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=5

install:
  - set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%
  - ps: Start-FileDownload 'https://github.com/mcmilk/7-Zip-zstd/releases/download/19.00-v1.4.8-R1/Codecs.7z'
  - 7z x Codecs.7z -o"C:\Program Files\7-Zip\Codecs"
  - conda install anaconda-clean -y
  - anaconda-clean --yes
  - C:\Miniconda3-x64\Uninstall-Miniconda3.exe /S
  - ps: Start-FileDownload 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe'
  - start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3

build_script:
  - conda config --set always_yes yes --set changeps1 no --set channel_priority strict
  - conda update -q conda
  - conda create -n mambaenv -c conda-forge conda-pack mamba python==3.7
  - activate mambaenv
  - mamba env create -f environment.yml
  - conda list -n %CONDA_ENV_NAME% > package-list.txt
  - >-
    conda pack --n-threads -1
    --exclude "*.pyc" --exclude "*.pyx"
    --name %CONDA_ENV_NAME%
    --output %CONDA_ENV_NAME%.tar
  - >-
    7z a %CONDA_ENV_NAME%.7z
    -m0=bcj -m1=zstd -mmt=4
    -mx12
    %CONDA_ENV_NAME%.tar

artifacts:
  - path: $(CONDA_ENV_NAME).7z
    name: Packed Environment
  - path: package-list.txt
    name: Installed Packages (conda list)
