version: 1.0.{build}
build: off

install:
  - set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c conda-forge conda-pack
  - conda init powershell
  - conda init cmd.exe
  - conda env create -f environment.yml
  - "conda pack -n conda-pack-build -o packed-env.tar.gz"
  - 7z a packed-env.tar.gz.xz packed-env.tar.gz

artifacts:
  - path: packed-env.tar.gz.xz
    name: Packed Environment
# test_script:
#   - cmd: conda help
