version: 1.0.{build}
build: off

install:
  - set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c conda-forge conda-pack
  - "conda create -n conda-pack-build python=3.7"
  - conda activate conda-pack-build
  - conda install -c conda-forge sentence-transformers
  - conda install pytorch torchvision torchaudio cpuonly -c pytorch
  - conda activate base
  - "conda pack -n conda-pack-build -o packed-env.tar.gz"

artifacts:
  - path: packed-env.tar.gz
    name: Packed Environment
# test_script:
#   - cmd: conda help
