name: conda-pack-build
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  # pytorch for transformers
  - torchvision
  - torchaudio
  - pytorch
  - cpuonly
  # sentence-transformers for embedding
  - sentence-transformers==0.3.9
  # data access / storage
  - pandas
  - zarr
  - openpyxl
  - xlsxwriter
  - sas7bdat
  - pymssql
  - pyarrow
  - tabulate
  # visualization
  - matplotlib
  - altair
  - altair_viewer
  - vega
  # analysis + ML
  - umap-learn
  - pynndescent
  - hdbscan
  # logging + configuration + admin
  - omegaconf
  - loguru
  # code quality helpers
  - black
  - flake8
  # PIP installs
  - pip
  - pip:
      - pysbd
      - onnxruntime
