name: conda-pack-build
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - torchvision
  - torchaudio
  - pytorch
  - cpuonly
  - sentence-transformers==0.3.9
  - zarr
  - pandas
  - openpyxl
  - xlsxwriter
  - black
  - flake8
  - pip
  - pip:
      - pysbd
      - onnxruntime
