name: conda-pack-build
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython
  # pytorch for transformers
  - pytorch==1.7.1
  - cpuonly
  # sentence-transformers for embedding
  - sentence-transformers==2.0.0
  # data access / storage
  - pandas
  - zarr
  - openpyxl
  - xlsxwriter
  - sas7bdat
  - pymssql
  - fastparquet
  - snappy
  - python-snappy
  - tabulate
  - spacy
  # visualization
  - matplotlib
  - altair
  - altair_viewer
  - plotly
  - dash
  - dash-bootstrap-components
  # analysis + ML
  - umap-learn
  - pynndescent
  - hdbscan
  - snorkel==0.9.7
  - cleanlab
  - scikit-learn
  - scikit-learn-intelex
  # logging + configuration + admin
  - omegaconf
  - loguru
  - python-dotenv
  - joblib==0.17.0
  # code quality helpers
  - black
  - flake8
  # PIP installs
  - pip
  - pip:
      - pysbd
      - apricot-select
      # - git+https://github.com/pmbaumgartner/embuddy.git
      # - onnxruntime
