name: conda-pack-build
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # pytorch for transformers
  - pytorch==1.7.1
  - cpuonly
  # sentence-transformers for embedding
  - sentence-transformers==2.0.0
  # data access / storage
  - pandas
  - zarr
  - openpyxl
  - xlsxwriter
  - sas7bdat
  - pymssql
  - fastparquet
  - snappy
  - python-snappy
  - tabulate
  # visualization
  - matplotlib
  - altair
  - altair_viewer
  - plotly
  - dash
  - dash-bootstrap-components
  # analysis + ML
  - umap-learn
  - pynndescent
  - hdbscan
  # logging + configuration + admin
  - omegaconf
  - loguru
  - python-dotenv
  - joblib==0.17.0
  # code quality helpers
  - black
  - flake8
  # PIP installs
  - pip
  - pip:
      - pysbd
      # - onnxruntime
