# These are built out due to how mamba handles a deprecated conda feature.
# Which results in us unable to install pytorch CPU only
# see: https://github.com/pytorch/builder/pull/488
name: conda-pack-build
channels:
  - conda-forge
  - defaults
dependencies:
  # sentence-transformers for embedding
  - sentence-transformers==0.3.9
  # data access / storage
  - pandas
  - zarr
  - openpyxl
  - xlsxwriter
  - sas7bdat
  - pymssql
  - fastparquet
  - tabulate
  # visualization
  - matplotlib
  - altair
  - altair_viewer
  - plotly
  # analysis + ML
  - umap-learn
  - pynndescent
  - hdbscan
  # logging + configuration + admin
  - omegaconf
  - loguru
  - python-dotenv
  # code quality helpers
  - black
  - flake8
  # PIP installs
  - pip
  - pip:
      - pysbd
      # - onnxruntime
